### ISSUE TITLE
Convert readme to readme.Rmd and get graphs to plot

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/EGRET#104]
I think you could take the readme as it is, save it as a .Rmd file, add the appropriate header, `knit` it, and we'd have a fancy readme with lots of graphs. This could then be the "testing platform" for our graphs:

```
---
title: "README"
author: "R"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  md_document:
    variant: markdown_github
---
```

Also would need to remember to add the .Rmd and corresponding images to the .Rbuildignore
